### ISSUE TITLE
(Feature request) Ship sheet upgrades

### ISSUE THREAD

**Issue by Orlanth-Rex** [ELH-mk1/sta2e#3]
- Enable system breaches to reduce number of successes rolled (p.310 of core rules)
- Add 'system destroyed' check box to sheet, with any rolls made using this system auto failing (p.311)

**Comment by ELH-mk1** [comment]
Added the System Destroyed functionality in v1.0.4 with the help of [Maxim-Alexandre Lalancette](https://github.com/malalancette). The breaches don't necessarily reduce number of successes rolled (as far as I understand it), so I left that alone for now. If I'm missing an important sentence or two, open another issue please!
