### ISSUE TITLE
Talent and Species Abilities validations to add Stress Points to the Stress Track

### ISSUE THREAD

**Issue by malalancette** [ELH-mk1/sta2e#4]
Inside the `stressTrackUpdate()`, between these lines https://github.com/ELH-mk1/sta2e/blame/ab9183b426da60bc67f474367570eabb575ca425/src/module/actors/sheets/character-sheet.js#L148-L159, you check for the exact name of the Talent, Species Ability, etc.

What I found by adding the Species Abilities as items is that I wanted to put the species' name before the name of the ability to quickly find the ability for a chosen species. Also, the ability name for the Aenar and the Betazoid is the same, `Telephatic`.

So, instead of validating the exact name of the ability, you could check if the ability/talent name CONTAINS the name.

So, instead of 

```javascript
[data-talent-name="Mental Discipline"]
``` 

it could be

```javascript
[data-talent-name~="Mental Discipline"]
``` 

as per this [CSS Selector](https://www.w3schools.com/cssref/sel_attribute_value_contains.php).

I don't know if it could be applied to all the cases, I'll let you be the judge of that.

**Comment by ELH-mk1** [comment]
Looks like it needs to be
```javascript
[data-talent-name*="Mental Discipline"]
```
In order to work properly. This will be fixed in the next version!

**Comment by malalancette** [comment]
Yes, you are right. I just tested the two selectors and it is yours that works.

Also, if I want to ask questions about this system and it is not about an issue, where can I do that?

And finally, if I wanted to help you with the system, is it possible? I am a front-end web developper with close to 20 years of experience, so I know my way around HTML, CSS and JavaScript. :)

**Comment by ELH-mk1** [comment]
Just drop me a line via email (elhmk1 @ gmail) or Discord (elhmk1). Always happy to chat!
